# Generated by Django 6.0.2 on 2026-03-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Полное название курса.', max_length=255, verbose_name='Название курса')),
                ('category', models.CharField(help_text='Например: IT Технологии, Языковые курсы, Реабилитация.', max_length=120, verbose_name='Категория')),
                ('short_description', models.TextField(help_text='Краткое описание для карточки курса.', verbose_name='Краткое описание')),
                ('full_description', models.TextField(help_text='Полное описание для детальной страницы курса.', verbose_name='Полное описание')),
                ('duration_text', models.CharField(help_text='Например: 4 месяца или 6 месяцев.', max_length=120, verbose_name='Текст длительности')),
                ('duration_months', models.PositiveIntegerField(help_text='Число месяцев для работы фильтра.', verbose_name='Длительность в месяцах')),
                ('level', models.CharField(help_text='Например: Начальный, Средний, Продвинутый.', max_length=120, verbose_name='Уровень')),
                ('students_count', models.PositiveIntegerField(help_text='Сколько студентов обучается.', verbose_name='Количество студентов')),
                ('lessons_count', models.PositiveIntegerField(help_text='Общее количество уроков в курсе.', verbose_name='Количество уроков')),
                ('price_text', models.CharField(default='Бесплатно', help_text='Например: Бесплатно.', max_length=120, verbose_name='Текст цены')),
                ('author', models.CharField(help_text='Имя автора курса.', max_length=255, verbose_name='Автор/преподаватель')),
                ('publication_year', models.PositiveIntegerField(help_text='Год публикации материала.', verbose_name='Год публикации')),
                ('source_name', models.CharField(help_text='Название источника или организации.', max_length=255, verbose_name='Источник')),
                ('source_url', models.CharField(blank=True, help_text='Ссылка на источник.', max_length=255, verbose_name='Ссылка на источник')),
                ('image_url', models.URLField(help_text='Ссылка на изображение карточки.', verbose_name='Изображение курса')),
                ('pdf_file', models.FileField(blank=True, help_text='Файл PDF для чтения.', null=True, upload_to='courses/pdfs/', verbose_name='PDF-файл курса')),
                ('audio_file', models.FileField(blank=True, help_text='Аудиоверсия материала.', null=True, upload_to='courses/audio/', verbose_name='Аудиофайл курса')),
                ('is_published', models.BooleanField(default=True, help_text='Показывать ли курс на сайте.', verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Полный заголовок новости.', max_length=255, verbose_name='Заголовок новости')),
                ('category', models.CharField(help_text='Например: Мировые новости, Мероприятия.', max_length=120, verbose_name='Категория')),
                ('short_description', models.TextField(help_text='Краткое описание для карточки.', verbose_name='Краткое описание')),
                ('content', models.TextField(help_text='Полный текст новости.', verbose_name='Полный текст новости')),
                ('image_url', models.URLField(help_text='Ссылка на главное изображение.', verbose_name='Изображение новости')),
                ('published_at', models.DateTimeField(help_text='Дата и время публикации.', verbose_name='Дата публикации')),
                ('author', models.CharField(help_text='Автор новости.', max_length=255, verbose_name='Автор')),
                ('source_name', models.CharField(help_text='Источник публикации.', max_length=255, verbose_name='Источник')),
                ('source_url', models.CharField(blank=True, help_text='Ссылка на внешний источник.', max_length=255, verbose_name='Ссылка на источник')),
                ('read_time', models.CharField(help_text='Например: 5 мин чтения.', max_length=120, verbose_name='Время чтения')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('tags_text', models.CharField(blank=True, help_text='Перечислите теги через запятую.', max_length=255, verbose_name='Теги')),
                ('is_published', models.BooleanField(default=True, help_text='Показывать ли новость на сайте.', verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название материала.', max_length=255, verbose_name='Название материала')),
                ('description', models.TextField(help_text='Краткое описание.', verbose_name='Описание материала')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF документ'), ('audio', 'Аудио'), ('video', 'Видео')], help_text='Выберите тип: PDF, аудио или видео.', max_length=10, verbose_name='Тип материала')),
                ('author', models.CharField(help_text='Автор или лектор.', max_length=255, verbose_name='Автор')),
                ('source_name', models.CharField(help_text='Источник или организация.', max_length=255, verbose_name='Источник')),
                ('source_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на источник')),
                ('year', models.PositiveIntegerField(help_text='Год публикации.', verbose_name='Год')),
                ('pages_count', models.PositiveIntegerField(blank=True, help_text='Для PDF-материалов.', null=True, verbose_name='Количество страниц')),
                ('duration_text', models.CharField(blank=True, help_text='Для аудио и видео. Например: 45 мин.', max_length=120, verbose_name='Длительность')),
                ('file_size', models.CharField(help_text='Например: 4.2 МБ.', max_length=120, verbose_name='Размер файла')),
                ('quality_text', models.CharField(blank=True, help_text='Только для видео. Например: HD 1080p.', max_length=120, verbose_name='Качество видео')),
                ('thumbnail_url', models.URLField(help_text='Ссылка на обложку.', verbose_name='Изображение материала')),
                ('file', models.FileField(blank=True, help_text='Загрузите PDF или аудиофайл.', null=True, upload_to='resources/files/', verbose_name='Файл материала')),
                ('external_url', models.CharField(blank=True, help_text='Ссылка на скачивание или YouTube.', max_length=255, verbose_name='Внешняя ссылка')),
                ('embed_url', models.CharField(blank=True, help_text='Только для видео.', max_length=255, verbose_name='Ссылка для встраивания')),
                ('is_published', models.BooleanField(default=True, help_text='Показывать ли материал на сайте.', verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Учебный материал',
                'verbose_name_plural': 'Учебные материалы',
                'ordering': ['resource_type', 'title'],
            },
        ),
    ]
