# Generated by Django 6.0.2 on 2026-03-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение с компьютера.', null=True, upload_to='courses/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ИТ Технологии', 'ИТ Технологии'), ('Языковые курсы', 'Языковые курсы'), ('Реабилитация', 'Реабилитация'), ('Творческие специальности', 'Творческие специальности'), ('Профессиональное образование', 'Профессиональное образование'), ('Личностное развитие', 'Личностное развитие'), ('Здоровье и спорт', 'Здоровье и спорт'), ('Социальная адаптация', 'Социальная адаптация'), ('Другое', 'Другое')], help_text='Выберите категорию курса.', max_length=120, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_text',
            field=models.CharField(choices=[('1 неделя', '1 неделя'), ('15 дней', '15 дней'), ('1 месяц', '1 месяц'), ('3 месяца', '3 месяца'), ('6 месяцев и более', '6 месяцев и более')], help_text='Выберите продолжительность курса.', max_length=120, verbose_name='Текст длительности'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на изображение карточки.', null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Начальный', 'Начальный'), ('Средний', 'Средний'), ('Продвинутый', 'Продвинутый')], help_text='Выберите уровень сложности.', max_length=120, verbose_name='Уровень'),
        ),
    ]
