# Generated by Django 6.0.2 on 2026-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_course_duration_months_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение с компьютера.', null=True, upload_to='news/', verbose_name='Изображение новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Международные новости', 'Международные новости'), ('Мероприятия', 'Мероприятия'), ('Образование', 'Образование'), ('Технологии', 'Технологии'), ('Достижения', 'Достижения'), ('Партнерство', 'Партнерство'), ('Объявления', 'Объявления'), ('Другое', 'Другое')], help_text='Выберите категорию новости.', max_length=120, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на главное изображение.', null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
