# Generated by Django 6.0.2 on 2026-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_image_alter_news_category_alter_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение с компьютера.', null=True, upload_to='resources/images/', verbose_name='Изображение материала'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Ссылка на обложку.', null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
