# Generated by Django 6.0.2 on 2026-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resource_image_alter_resource_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Полное имя основателя', max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(help_text='Должность основателя (например: Директор издательства)', max_length=255, verbose_name='Должность')),
                ('company', models.CharField(blank=True, help_text='Название организации', max_length=255, verbose_name='Организация')),
                ('photo', models.ImageField(blank=True, help_text='Фото основателя', null=True, upload_to='founder/', verbose_name='Фотография')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация об основателе', verbose_name='Краткая биография')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать блок основателя на странице "О нас"', verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Основатель',
                'verbose_name_plural': 'Основатели',
                'ordering': ['-created_at'],
            },
        ),
    ]
